//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HariOmImpex_LMS {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class bookmarks_settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static bookmarks_settings defaultInstance = ((bookmarks_settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new bookmarks_settings())));
        
        public static bookmarks_settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection bookmarks {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["bookmarks"]));
            }
            set {
                this["bookmarks"] = value;
            }
        }
    }
}
